# Generated by Django 4.2.30 on 2026-09-16 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('project_url', models.URLField(blank=True)),
                ('project_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('juniour high school', 'Junior High School'), ('senior high school', 'Senior High School'), ('university', 'University')], default='university', max_length=20),
        ),
    ]
